apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aquaculture-platform-base

namespace: aquaculture

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: aquaculture-platform
  app.kubernetes.io/managed-by: kustomize
