version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: aqua-mosquitto
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - aqua-simulator
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: aqua-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    environment:
      - TZ=Europe/Istanbul
    depends_on:
      - mosquitto
    networks:
      - aqua-simulator
    restart: unless-stopped

networks:
  aqua-simulator:
    driver: bridge
    name: aqua-simulator
